# This action syncs the wiki from the source repository to the wiki repository. It will be triggered whenever changes are detected in the wiki directory or the workflow file itself.
# Thanks to Justin Dehorty and Arnob Mallick, whose work on the [platform-mcp wiki](https://github.com/iTwin/platform-mcp/tree/main) heavily inspired this.

name: Publish Wiki from Source

on:
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki-sync.yml'

permissions: # lets the default token push to the wiki repo
  contents: write

concurrency: # cancels previous runs on the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repo
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Copy wiki directory to temp
        run: |
          rm -rf /tmp/wiki-content
          mkdir -p /tmp/wiki-content
          cp -r wiki/* /tmp/wiki-content/

      - name: Clone wiki repository
        run: |
          git clone "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git" /tmp/wiki

      - name: Generate new wiki content
        run: |
          rm -rf /tmp/wiki/*
          cp -r /tmp/wiki-content/* /tmp/wiki/

      - name: Add edit disclaimer and remove duplicate H1 titles
        run: |
          cd /tmp/wiki
          # First pass: Add disclaimer at the top of each file
          find . -name "*.md" -type f -exec sed -i '1s/^/<!-- DO NOT EDIT THIS FILE DIRECTLY. This wiki is automatically generated from the source repository. All changes must be made through pull requests to https:\/\/github.com\/iTwin\/platform-mcp\/tree\/main\/wiki -->\n\n/' {} +
          # Second pass: Remove H1 titles to prevent duplication
          find . -name "*.md" -type f -exec sed -i 's|^# \(.*\)$|<!-- original title: "\1" removed -->|g' {} +

      - name: Commit and push changes to wiki
        run: |
          cd /tmp/wiki
          git add .
          git commit -m "update wiki from source repo" || echo "nothing to commit"
          git push
